'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Checkbox } from '@/components/ui/checkbox'
import { Loader2, Plus, Trash2 } from 'lucide-react'
import { deletePipelineStage, saveCommissionRule, saveEnergyTariff, savePipelineStage, saveRole, saveUnit, toggleRolePermission } from '@/app/crm/administracao/actions'

type Role = { id: string; name: string; slug: string; description: string | null; parent_role_id: string | null; hierarchy_level: number; is_system: boolean }
type Permission = { id: string; code: string; name: string; module: string }
type Unit = { id: string; name: string; code: string; type: string; parent_unit_id: string | null; manager_id: string | null; city: string | null; position: number }
type Profile = { id: string; first_name: string; last_name: string; email: string | null }
type Stage = { id: string; segment: string; name: string; position: number; color: string; is_won: boolean; is_lost: boolean; is_active: boolean }
type Rule = { id: string; name: string; segment: string; scope_type: string; role_id: string | null; unit_id: string | null; profile_id: string | null; percentage: number; fixed_value: number | null; priority: number }
type Tariff = { id: string; supplier: string; plan_name: string; tariff_type: string; power_kva: number | null; energy_price_kwh: number; daily_fixed_price: number; valid_from: string; valid_until: string | null; last_verified_at: string | null }

const segments = ['energia', 'telecom', 'credito', 'imobiliario', 'seguros']

export function AdministracaoPanel({ roles, permissions, rolePermissions, units, profiles, stages, rules, tariffs }: { roles: Role[]; permissions: Permission[]; rolePermissions: { role_id: string; permission_id: string; allowed: boolean }[]; units: Unit[]; profiles: Profile[]; stages: Stage[]; rules: Rule[]; tariffs: Tariff[] }) {
  return (
    <Tabs defaultValue="cargos" className="space-y-5">
      <TabsList className="flex h-auto flex-wrap justify-start">
        <TabsTrigger value="cargos">Cargos e permissões</TabsTrigger>
        <TabsTrigger value="unidades">Unidades</TabsTrigger>
        <TabsTrigger value="pipeline">Pipeline</TabsTrigger>
        <TabsTrigger value="comissoes">Comissões</TabsTrigger>
        <TabsTrigger value="energia">Tarifários de energia</TabsTrigger>
      </TabsList>
      <TabsContent value="cargos"><RolesSection roles={roles} permissions={permissions} rolePermissions={rolePermissions} /></TabsContent>
      <TabsContent value="unidades"><UnitsSection units={units} profiles={profiles} /></TabsContent>
      <TabsContent value="pipeline"><PipelineSection stages={stages} /></TabsContent>
      <TabsContent value="comissoes"><CommissionSection rules={rules} roles={roles} units={units} profiles={profiles} /></TabsContent>
      <TabsContent value="energia"><EnergySection tariffs={tariffs} /></TabsContent>
    </Tabs>
  )
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-card p-5"><h2 className="mb-4 font-semibold">{title}</h2>{children}</section> }
function SelectField({ value, onChange, children }: { value: string; onChange: (v: string) => void; children: React.ReactNode }) { return <select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={(e) => onChange(e.target.value)}>{children}</select> }
function Submit({ pending, label = 'Guardar' }: { pending: boolean; label?: string }) { return <Button disabled={pending} className="bg-brand text-white">{pending && <Loader2 className="mr-2 animate-spin" size={15} />}{label}</Button> }

function RolesSection({ roles, permissions, rolePermissions }: { roles: Role[]; permissions: Permission[]; rolePermissions: { role_id: string; permission_id: string; allowed: boolean }[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [selected, setSelected] = useState(roles[0]?.id ?? '')
  const [form, setForm] = useState({ name: '', slug: '', description: '', parent_role_id: '', hierarchy_level: 0 })
  const allowed = new Set(rolePermissions.filter((x) => x.role_id === selected && x.allowed).map((x) => x.permission_id))
  const submit = (e: React.FormEvent) => { e.preventDefault(); start(async () => { const r = await saveRole(form); if (!r.ok) { toast.error(r.error); return }; toast.success('Cargo criado'); setForm({ name: '', slug: '', description: '', parent_role_id: '', hierarchy_level: 0 }); router.refresh() }) }
  return <div className="grid gap-5 xl:grid-cols-[360px_1fr]">
    <Card title="Novo cargo hierárquico"><form onSubmit={submit} className="space-y-3"><Input required placeholder="Nome do cargo" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value, slug: form.slug || e.target.value })} /><Input required placeholder="Identificador" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} /><Input placeholder="Descrição" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Label>Cargo superior</Label><SelectField value={form.parent_role_id} onChange={(v) => setForm({ ...form, parent_role_id: v })}><option value="">Sem superior</option>{roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</SelectField><Input type="number" min={0} placeholder="Nível" value={form.hierarchy_level} onChange={(e) => setForm({ ...form, hierarchy_level: +e.target.value })} /><Submit pending={pending} label="Criar cargo" /></form></Card>
    <Card title="Matriz de permissões"><SelectField value={selected} onChange={setSelected}>{roles.map((r) => <option key={r.id} value={r.id}>{r.name}</option>)}</SelectField><div className="mt-4 grid gap-3 md:grid-cols-2">{permissions.map((p) => <label key={p.id} className="flex items-start gap-3 rounded-lg border p-3"><Checkbox checked={allowed.has(p.id)} onCheckedChange={(v) => start(async () => { const r = await toggleRolePermission({ role_id: selected, permission_id: p.id, allowed: Boolean(v) }); if (!r.ok) toast.error(r.error); else router.refresh() })} /><span><b className="block text-sm">{p.name}</b><span className="text-xs text-muted-foreground">{p.module} · {p.code}</span></span></label>)}</div></Card>
  </div>
}

function UnitsSection({ units, profiles }: { units: Unit[]; profiles: Profile[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [form, setForm] = useState({ name: '', code: '', type: 'agencia', parent_unit_id: '', manager_id: '', city: '', position: 0 })
  const submit = (e: React.FormEvent) => { e.preventDefault(); start(async () => { const r = await saveUnit(form); if (!r.ok) { toast.error(r.error); return }; toast.success('Unidade criada'); setForm({ name: '', code: '', type: 'agencia', parent_unit_id: '', manager_id: '', city: '', position: 0 }); router.refresh() }) }
  return <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card title="Criar unidade"><form onSubmit={submit} className="space-y-3"><Input required placeholder="Nome" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required placeholder="Código" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /><SelectField value={form.type} onChange={(v) => setForm({ ...form, type: v })}>{['sede','agencia','franquia','parceiro'].map((x) => <option key={x}>{x}</option>)}</SelectField><Label>Unidade superior</Label><SelectField value={form.parent_unit_id} onChange={(v) => setForm({ ...form, parent_unit_id: v })}><option value="">Sem superior</option>{units.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</SelectField><Label>Responsável</Label><SelectField value={form.manager_id} onChange={(v) => setForm({ ...form, manager_id: v })}><option value="">Sem responsável</option>{profiles.map((p) => <option key={p.id} value={p.id}>{p.first_name} {p.last_name}</option>)}</SelectField><Input placeholder="Cidade" value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /><Submit pending={pending} label="Criar unidade" /></form></Card><Card title="Organograma">{units.map((u) => <div key={u.id} className="mb-2 rounded-lg border p-3" style={{ marginLeft: Math.min(48, (units.find((p) => p.id === u.parent_unit_id) ? 24 : 0)) }}><b>{u.name}</b><p className="text-xs text-muted-foreground">{u.type} · {u.code}{u.city ? ` · ${u.city}` : ''}</p></div>)}</Card></div>
}

function PipelineSection({ stages }: { stages: Stage[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [segment, setSegment] = useState('energia'); const [form, setForm] = useState({ name: '', position: 0, color: '#0057FF', is_won: false, is_lost: false })
  const list = stages.filter((s) => s.segment === segment).sort((a,b) => a.position-b.position)
  const submit = (e: React.FormEvent) => { e.preventDefault(); start(async () => { const r = await savePipelineStage({ ...form, segment, is_active: true }); if (!r.ok) { toast.error(r.error); return }; toast.success('Etapa criada'); setForm({ name: '', position: list.length, color: '#0057FF', is_won: false, is_lost: false }); router.refresh() }) }
  return <div className="space-y-5"><SelectField value={segment} onChange={setSegment}>{segments.map((s) => <option key={s}>{s}</option>)}</SelectField><div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card title="Nova etapa"><form onSubmit={submit} className="space-y-3"><Input required placeholder="Nome" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input type="number" placeholder="Posição" value={form.position} onChange={(e) => setForm({ ...form, position: +e.target.value })} /><Input type="color" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /><label className="flex gap-2 text-sm"><Checkbox checked={form.is_won} onCheckedChange={(v) => setForm({ ...form, is_won: Boolean(v), is_lost: false })} />Etapa ganha</label><label className="flex gap-2 text-sm"><Checkbox checked={form.is_lost} onCheckedChange={(v) => setForm({ ...form, is_lost: Boolean(v), is_won: false })} />Etapa perdida</label><Submit pending={pending} label="Adicionar etapa" /></form></Card><Card title="Etapas atuais">{list.map((s) => <div key={s.id} className="mb-2 flex items-center gap-3 rounded-lg border p-3"><span className="h-3 w-3 rounded-full" style={{ background: s.color }} /><span className="flex-1"><b>{s.position + 1}. {s.name}</b>{(s.is_won || s.is_lost) && <small className="ml-2 text-muted-foreground">{s.is_won ? 'Ganha' : 'Perdida'}</small>}</span><Button variant="ghost" size="icon" onClick={() => start(async () => { const r = await deletePipelineStage(s.id); if (!r.ok) toast.error(r.error); else router.refresh() })}><Trash2 size={15} /></Button></div>)}</Card></div></div>
}

function CommissionSection({ rules, roles, units, profiles }: { rules: Rule[]; roles: Role[]; units: Unit[]; profiles: Profile[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [form, setForm] = useState({ name: '', segment: 'energia', scope_type: 'global', target: '', percentage: 0, fixed_value: 0, priority: 0 })
  const submit = (e: React.FormEvent) => { e.preventDefault(); start(async () => { const r = await saveCommissionRule({ name: form.name, segment: form.segment, scope_type: form.scope_type, role_id: form.scope_type === 'role' ? form.target : undefined, unit_id: form.scope_type === 'unit' ? form.target : undefined, profile_id: form.scope_type === 'user' ? form.target : undefined, percentage: form.percentage, fixed_value: form.fixed_value, priority: form.priority }); if (!r.ok) { toast.error(r.error); return }; toast.success('Regra criada'); router.refresh() }) }
  const targets = form.scope_type === 'role' ? roles.map((x) => ({ id:x.id,name:x.name })) : form.scope_type === 'unit' ? units.map((x) => ({ id:x.id,name:x.name })) : form.scope_type === 'user' ? profiles.map((x) => ({ id:x.id,name:`${x.first_name} ${x.last_name}` })) : []
  return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><Card title="Nova regra de comissão"><form onSubmit={submit} className="space-y-3"><Input required placeholder="Nome da regra" value={form.name} onChange={(e) => setForm({ ...form, name:e.target.value })} /><SelectField value={form.segment} onChange={(v) => setForm({ ...form, segment:v })}>{segments.map((s) => <option key={s}>{s}</option>)}</SelectField><SelectField value={form.scope_type} onChange={(v) => setForm({ ...form, scope_type:v, target:'' })}>{['global','role','unit','user'].map((s) => <option key={s} value={s}>{({global:'Global',role:'Cargo',unit:'Unidade',user:'Utilizador'} as Record<string,string>)[s]}</option>)}</SelectField>{targets.length > 0 && <SelectField value={form.target} onChange={(v) => setForm({ ...form, target:v })}><option value="">Selecionar…</option>{targets.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</SelectField>}<Label>Percentagem</Label><Input type="number" step="0.01" value={form.percentage} onChange={(e) => setForm({ ...form, percentage:+e.target.value })} /><Label>Valor fixo (€)</Label><Input type="number" step="0.01" value={form.fixed_value} onChange={(e) => setForm({ ...form, fixed_value:+e.target.value })} /><Submit pending={pending} label="Criar regra" /></form></Card><Card title="Regras por segmento e âmbito"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Regra</th><th>Segmento</th><th>Âmbito</th><th>%</th><th>Fixo</th></tr></thead><tbody>{rules.map((r) => <tr key={r.id} className="border-b"><td className="p-2 font-medium">{r.name}</td><td>{r.segment}</td><td>{r.scope_type}</td><td>{r.percentage}%</td><td>{r.fixed_value ? `${r.fixed_value}€` : '—'}</td></tr>)}</tbody></table></div></Card></div>
}

function EnergySection({ tariffs }: { tariffs: Tariff[] }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [form, setForm] = useState({ supplier: '', plan_name: '', tariff_type: 'simples', power_kva: 6.9, energy_price_kwh: 0, daily_fixed_price: 0, source_url: '', valid_from: new Date().toISOString().slice(0,10), valid_until: '' })
  const submit = (e: React.FormEvent) => { e.preventDefault(); start(async () => { const r = await saveEnergyTariff(form); if (!r.ok) { toast.error(r.error); return }; toast.success('Tarifário guardado e verificado'); router.refresh() }) }
  return <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><Card title="Adicionar/atualizar tarifário"><form onSubmit={submit} className="space-y-3"><Input required placeholder="Comercializador" value={form.supplier} onChange={(e) => setForm({ ...form, supplier:e.target.value })} /><Input required placeholder="Plano" value={form.plan_name} onChange={(e) => setForm({ ...form, plan_name:e.target.value })} /><SelectField value={form.tariff_type} onChange={(v) => setForm({ ...form, tariff_type:v })}>{['simples','bi-horario','tri-horario'].map((x) => <option key={x}>{x}</option>)}</SelectField><Label>Potência (kVA)</Label><Input type="number" step="0.01" value={form.power_kva} onChange={(e) => setForm({ ...form, power_kva:+e.target.value })} /><Label>Preço energia €/kWh</Label><Input required type="number" step="0.000001" value={form.energy_price_kwh} onChange={(e) => setForm({ ...form, energy_price_kwh:+e.target.value })} /><Label>Preço fixo €/dia</Label><Input type="number" step="0.000001" value={form.daily_fixed_price} onChange={(e) => setForm({ ...form, daily_fixed_price:+e.target.value })} /><Input type="url" placeholder="Fonte oficial" value={form.source_url} onChange={(e) => setForm({ ...form, source_url:e.target.value })} /><Input type="date" value={form.valid_from} onChange={(e) => setForm({ ...form, valid_from:e.target.value })} /><Submit pending={pending} label="Guardar tarifário" /></form></Card><Card title="Tarifários ativos"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Fornecedor</th><th>Plano</th><th>Potência</th><th>€/kWh</th><th>€/dia</th><th>Verificado</th></tr></thead><tbody>{tariffs.map((t) => <tr key={t.id} className="border-b"><td className="p-2 font-medium">{t.supplier}</td><td>{t.plan_name}</td><td>{t.power_kva ?? '—'}</td><td>{Number(t.energy_price_kwh).toFixed(6)}</td><td>{Number(t.daily_fixed_price).toFixed(4)}</td><td>{t.last_verified_at ? new Date(t.last_verified_at).toLocaleDateString('pt-PT') : 'Pendente'}</td></tr>)}</tbody></table></div></Card></div>
}
